# Generated by Django 4.0 on 2021-12-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_site', '0002_alter_authors_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='scholar_link',
            new_name='link',
        ),
    ]
