# Generated by Django 4.0 on 2021-12-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_site', '0003_rename_scholar_link_authors_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='affiliation',
            field=models.CharField(default='N\\A', max_length=1000),
        ),
        migrations.AddField(
            model_name='authors',
            name='citations',
            field=models.CharField(default='N\\A', max_length=1000),
        ),
        migrations.AddField(
            model_name='authors',
            name='email',
            field=models.CharField(default='N\\A', max_length=100),
        ),
    ]
