# Generated by Django 4.0 on 2022-01-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_site', '0004_authors_affiliation_authors_citations_authors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
